export const SUMAR_PRODUCTO = "SUMAR_PRODUCTO";
export const RESTAR_PRODUCTO = "RESTAR_PRODUCTO";
export const AGREGAR_PRODUCTO = "AGREGAR_PRODUCTO";
export const ELIMINAR_PRODUCTO = "ELIMINAR_PRODUCTO";
export const LIMPIAR_CARTA = "LIMPIAR_CARTA";
export const CHECKOUT = "CHECKOUT";
